### ISSUE TITLE
Forge server not working

### ISSUE THREAD

**Issue by Sgarbino** [Divine-Journey-2/Divine-Journey-2#271]
**Modpack version:**
2.3.0

**Description:**
The forge server does not work and produces errors.

**Steps to reproduce:**
1. Install and extract serverpack into empty file.
2. Double click either run or the forge jar file itself.

**Expected behaviour:**
I expected the server to start up and load a world.

**Screenshots:**
https://gyazo.com/75ba61cce2256fd8dd8b13677be48795

**Additional context:**
Error in cmd shell:

A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
        at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        ... 6 more
Press any key to continue . . .

**Notes:**
- Yes I did set the eula to true.
- Yes I did change a few things in the bat file:
@ECHO OFF
java -server -Xms4G -Xmx9G -jar forge-1.12.2-14.23.5.2855.jar nogui
pause

- Yes I received the same result without edited bat file.

**Comment by WaitingIdly** [comment]
you have not identified your java version. please update your java version to the latest JRE 8

**Comment by Sgarbino** [comment]
> you have not identified your java version. please update your java version to the latest JRE 8

I've got the latest version of java according to the updater. https://gyazo.com/7f2cf6f775d1cdb33823be7d2b487a83

**Comment by Atricos** [comment]
Update your Java Runtime Environment.

**Comment by Atricos** [comment]
The server files seem to be working, so the issue not on our end.
