### ISSUE TITLE
server wont open

### ISSUE THREAD

**Issue by Mueann** [Divine-Journey-2/Divine-Journey-2#672]
### Modpack version

newst

### Java version

jdk1.8.0_331

### RAM Allocated

8/16

### Description

i downloaded the serverpack and tried to run a server but it wont open

### When did the crash happen?

just happend

### Steps to reproduce

download the serverpack, run the server

### Minecraft crash report

```
G:\mcserver\Divine+Journey+2.14.2+Server+Pack>"C:\Program Files\Java\jre1.8.0_331\bin\java.exe" -Xms4096M -Xmx8192M -jar forge-1.12.2-14.23.5.2860.jar nogui
2022-05-25 18:35:10,176 main WARN Disabling terminal, you're running in an unsupported environment.
[18:35:10] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLServerTweaker
[18:35:10] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLServerTweaker
[18:35:10] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLServerTweaker
[18:35:10] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2860 for Minecraft 1.12.2 loading
[18:35:10] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_331, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_331
[18:35:10] [main/INFO] [FML]: Searching G:\mcserver\Divine+Journey+2.14.2+Server+Pack\.\mods for mods
[18:35:10] [main/INFO] [FML]: Searching G:\mcserver\Divine+Journey+2.14.2+Server+Pack\.\mods\1.12.2 for mods
[18:35:10] [main/WARN] [FML]: The coremod portablejim.additionalresources.Ar_CorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:35:10] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in astral-level-nerf-1.0.1-all.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[18:35:10] [main/WARN] [FML]: The coremod AstralLevelNerfPlugin (mixu.astrallevelnerf.asm.AstralLevelNerfPlugin) is not signed!
[18:35:10] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in astralsorcery-1.12.2-1.10.27.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[18:35:10] [main/WARN] [FML]: The coremod hellfirepvp.astralsorcery.core.AstralCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:35:10] [main/INFO] [Astral Core]: [AstralCore] Initialized.
[18:35:10] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in bedpatch-2.2-1.12.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[18:35:10] [main/INFO] [FML]: Loading tweaker guichaguri.betterfps.tweaker.BetterFpsTweaker from BetterFps-1.4.8.jar
[18:35:10] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from bewitchment-1.12.2-0.0.22.64.jar
[18:35:10] [main/WARN] [FML]: The coremod com.bloodnbonesgaming.bnbgamingcore.core.BNBGamingCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:35:10] [main/WARN] [FML]: The coremod BNBGamingCore (com.bloodnbonesgaming.bnbgamingcore.core.BNBGamingCorePlugin) is not signed!
[18:35:10] [main/INFO] [FML]: Loading tweaker codechicken.asm.internal.Tweaker from ChickenASM-1.12-1.0.2.7.jar
[18:35:10] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from dj2addons-1.0.1.jar
[18:35:10] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from DupeFixProject-1.12.2-3.1.6.jar
[18:35:10] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from erebusfix-1.12.2-0.0.0.1.jar
[18:35:10] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in foamfix-0.10.14-1.12.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[18:35:10] [main/WARN] [FML]: The coremod pl.asie.foamfix.coremod.FoamFixCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:35:10] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in Forgelin-1.8.4.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[18:35:10] [main/WARN] [FML]: The coremod net.shadowfacts.forgelin.preloader.ForgelinPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:35:10] [main/WARN] [FML]: The coremod ForgelinPlugin (net.shadowfacts.forgelin.preloader.ForgelinPlugin) is not signed!
[18:35:10] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in HammerLib-1.12.2-2.0.6.28.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[18:35:10] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in InventoryTweaks-1.63.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[18:35:10] [main/WARN] [FML]: The coremod invtweaks.forge.asm.FMLPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:35:11] [main/WARN] [FML]: The coremod ivorius.ivtoolkit.IvToolkitLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:35:11] [main/WARN] [FML]: The coremod IvToolkit (ivorius.ivtoolkit.IvToolkitLoadingPlugin) is not signed!
[18:35:11] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in librarianlib-1.12.2-4.22.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[18:35:11] [main/WARN] [FML]: The coremod com.teamwizardry.librarianlib.asm.LibLibCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:35:11] [main/WARN] [FML]: The coremod LibrarianLib Plugin (com.teamwizardry.librarianlib.asm.LibLibCorePlugin) is not signed!
[18:35:11] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in Mekanism-1.12.2-9.8.3.390.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[18:35:11] [main/WARN] [FML]: The coremod mekanism.coremod.MekanismCoremod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:35:11] [main/WARN] [FML]: The coremod MekanismCoremod (mekanism.coremod.MekanismCoremod) is not signed!
[18:35:11] [main/WARN] [FML]: The coremod micdoodle8.mods.miccore.MicdoodlePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:35:11] [main/WARN] [FML]: The coremod MicdoodlePlugin (micdoodle8.mods.miccore.MicdoodlePlugin) is not signed!
[18:35:11] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in NotEnoughIDs-1.5.4.4.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[18:35:11] [main/WARN] [FML]: The coremod ru.fewizz.neid.asm.Plugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:35:11] [main/WARN] [FML]: The coremod Plugin (ru.fewizz.neid.asm.Plugin) is not signed!
[18:35:11] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in OpenModsLib-1.12.2-0.12.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[18:35:11] [main/WARN] [FML]: The coremod openmods.core.OpenModsCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:35:11] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in Quark-r1.6-179.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[18:35:11] [main/WARN] [FML]: The coremod Quark Plugin (vazkii.quark.base.asm.LoadingPlugin) is not signed!
[18:35:11] [main/WARN] [FML]: The coremod com.therandomlabs.randompatches.core.RPCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:35:11] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in ThaumicAugmentation-1.12.2-2.1.5.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[18:35:11] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.RuntimeException: An error occurred trying to configure the Minecraft home at G:\mcserver\Divine+Journey+2.14.2+Server+Pack\. for Forge Mod Loader
        at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:111) ~[forge-1.12.2-14.23.5.2860.jar:?]
        at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupServer(FMLLaunchHandler.java:87) ~[forge-1.12.2-14.23.5.2860.jar:?]
        at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForServerLaunch(FMLLaunchHandler.java:47) ~[forge-1.12.2-14.23.5.2860.jar:?]
        at net.minecraftforge.fml.common.launcher.FMLServerTweaker.injectIntoClassLoader(FMLServerTweaker.java:62) ~[forge-1.12.2-14.23.5.2860.jar:?]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_331]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_331]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_331]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_331]
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70) [forge-1.12.2-14.23.5.2860.jar:?]
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34) [forge-1.12.2-14.23.5.2860.jar:?]
Caused by: java.lang.ExceptionInInitializerError
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_331]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_331]
        at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:527) ~[forge-1.12.2-14.23.5.2860.jar:?]
        at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:451) ~[forge-1.12.2-14.23.5.2860.jar:?]
        at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:265) ~[forge-1.12.2-14.23.5.2860.jar:?]
        at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:107) ~[forge-1.12.2-14.23.5.2860.jar:?]
        ... 11 more
Caused by: java.lang.RuntimeException: java.lang.IllegalStateException: modsDir.listFiles() returned null! Attempted to index: \mcserver\Divine Journey 2.14.2 Server Pack\.\mods
        at com.github.terminatornl.tickcentral.loading.Loader.findTransformersInJarFiles(Loader.java:137) ~[Loader.class:3.2]
        at com.github.terminatornl.tickcentral.loading.Loader.<init>(Loader.java:38) ~[Loader.class:3.2]
        at com.github.terminatornl.tickcentral.TickCentral.<clinit>(TickCentral.java:37) ~[TickCentral-3.2.jar:3.2]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_331]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_331]
        at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:527) ~[forge-1.12.2-14.23.5.2860.jar:?]
        at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:451) ~[forge-1.12.2-14.23.5.2860.jar:?]
        at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:265) ~[forge-1.12.2-14.23.5.2860.jar:?]
        at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:107) ~[forge-1.12.2-14.23.5.2860.jar:?]
        ... 11 more
Caused by: java.lang.IllegalStateException: modsDir.listFiles() returned null! Attempted to index: \mcserver\Divine Journey 2.14.2 Server Pack\.\mods
        at com.github.terminatornl.tickcentral.loading.Loader.findTransformersInJarFiles(Loader.java:121) ~[Loader.class:3.2]
        at com.github.terminatornl.tickcentral.loading.Loader.<init>(Loader.java:38) ~[Loader.class:3.2]
        at com.github.terminatornl.tickcentral.TickCentral.<clinit>(TickCentral.java:37) ~[TickCentral-3.2.jar:3.2]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_331]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_331]
        at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:527) ~[forge-1.12.2-14.23.5.2860.jar:?]
        at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:451) ~[forge-1.12.2-14.23.5.2860.jar:?]
        at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:265) ~[forge-1.12.2-14.23.5.2860.jar:?]
        at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:107) ~[forge-1.12.2-14.23.5.2860.jar:?]
        ... 11 more
A problem occurred running the Server launcher.[18:35:11] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:34]: java.lang.reflect.InvocationTargetException
[18:35:11] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:34]:       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:35:11] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:34]:       at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[18:35:11] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:34]:       at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[18:35:11] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:34]:       at java.lang.reflect.Method.invoke(Unknown Source)
[18:35:11] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:34]:       at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70)
[18:35:11] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:34]:       at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34)
[18:35:11] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]: Caused by: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[18:35:11] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]:        at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[18:35:11] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]:        at java.lang.SecurityManager.checkExit(Unknown Source)
[18:35:11] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]:        at java.lang.Runtime.exit(Unknown Source)
[18:35:11] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]:        at java.lang.System.exit(Unknown Source)
[18:35:11] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]:        at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[18:35:11] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]:        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[18:35:11] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:75]:        ... 6 more
```

**Comment by luciscout** [comment]
This is due to an issue with TickCentral parsing + in your folder name. Please rename the folder containing your server to not include any + and confirm this resolves the issue

**Comment by Furryks** [comment]
I also faced this problem, I can't solve it.

**Comment by Preta-Crowz** [comment]
@Furryks If fix for this issue doesn't work, then you should open new issue and upload own log to fix.

**Comment by Furryks** [comment]
@Preta-Crowz I opened a request, I hope it will help me and not only me.
